CREATE TABLE  IF NOT EXISTS produtos_variacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    medida_completa VARCHAR(255),
    largura INTEGER,
    perfil INTEGER,
    aro INTEGER,
    indice_carga INTEGER,
    preco NUMERIC(38, 2),
    quantidade_estoque INTEGER,
    produto_id BIGINT,
    CONSTRAINT pk_produtos_variacao PRIMARY KEY (id),
    CONSTRAINT fk_produtos_variacao_on_produto
        FOREIGN KEY (produto_id) REFERENCES produtos (id)
);
