CREATE TABLE produto_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preco_unitario DOUBLE PRECISION,
    quantidade INTEGER,
    pedido_id BIGINT,
    produto_variacao_id BIGINT,

    CONSTRAINT fk_produto_pedido_pedido
        FOREIGN KEY (pedido_id)
        REFERENCES pedido(id),

    CONSTRAINT fk_produto_pedido_variacao
        FOREIGN KEY (produto_variacao_id)
        REFERENCES produtos_variacao(id)
);