CREATE TABLE carro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(255),
    modelo VARCHAR(255),
    ano_fabricacao INTEGER,
    versao VARCHAR(255)
);

CREATE TABLE carro_produto_variacao (
    carro_id BIGINT NOT NULL,
    produto_variacao_id BIGINT NOT NULL,

    CONSTRAINT pk_carro_produto_variacao
    PRIMARY KEY (carro_id, produto_variacao_id),
    CONSTRAINT fk_carro_produto_variacao_carro
        FOREIGN KEY (carro_id)
        REFERENCES carro(id),

    CONSTRAINT fk_carro_produto_variacao_variacao
        FOREIGN KEY (produto_variacao_id)
        REFERENCES produtos_variacao(id)
);